### ISSUE TITLE
Add command line support

### ISSUE THREAD

**Issue by nicholst** [pwilliams1/nidmresults-fslhtml#1]
Ensure that the viewer.py can be called on the command line, with a usage like

```
viewer.py results.nidm results.html
```

**Comment by pwilliams1** [comment]
I have started to work on this - Currently works on windows command line, e.g. viewer.py testResults.nidm

**Comment by cmaumet** [comment]
@pwilliams1: for an example on how to do this, you can have a look at: https://github.com/incf-nidash/nidmresults-fsl/blob/master/bin/nidmfsl.

**Comment by cmaumet** [comment]
Hi @pwilliams1, 

Once you have fixed this issue, I think it is time to create your first pull request! 

For now we will stay in your forked repository, so we are looking at creating a pull request of your [sample_viewer branch in pwilliams1/nidmresults-fslhtml](https://github.com/pwilliams1/nidmresults-fslhtml/tree/sample_viewer) onto the [master branch in pwilliams1/nidmresults-fslhtml](https://github.com/pwilliams1/nidmresults-fslhtml) so that we can have a first version of your code in the master branch.

To create this pull request: 
- follow this link: https://github.com/pwilliams1/nidmresults-fslhtml/compare/master...pwilliams1:sample_viewer?expand=1 
- briefly provide a description of the set of updates in the main text box (cf. [GitHub markdown notation](https://guides.github.com/features/mastering-markdown/)).
- click on `create pull request`

I will then review your code and send you feedback. By using pull requests for each new feature, we can merge the code incrementally and you can document each new set of changes as part of the pull request. Let me know if you have any question.

**Comment by pwilliams1** [comment]
Pull request created.

**Comment by cmaumet** [comment]
Fixed in #3.
